language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2

script:
  - bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=763e2fed349469f0d07de8278c7df59cc64b9b8aa8f2f178fb1e7c5efae1bc49 bundle exec codeclimate-test-reporter
